apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: "Pull Request Verify"
    context: "pr"
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  postsubmits:
  - name: Release
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
