apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "PR Verify"
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  postsubmits:
  - name: release
    context: "Release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
